version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    environment:
      VITE_ES_HOST: http://localhost:9200
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run build
          command: yarn build

workflows:
  ci-build-and-test:
    jobs:
      - build-and-test